name: "NLC AI"
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nlc_ai_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: nlc_ai_redis_gui
    restart: unless-stopped
    environment:
      REDIS_HOSTS: "render:${REDIS_HOST}"
    ports:
      - "8081:8081"

volumes:
  pgadmin_data:
    driver: local
