[build]
builder = "dockerfile"
dockerfilePath = "apps/api/gateway/Dockerfile"
watchPatterns = [
  "apps/api/gateway/**",
  "libs/api/**",
  "nx.json",
  "package.json",
  "tsconfig*.json"
]

[deploy]
preDeployCommand = ["npm run db:deploy"]
healthcheckPath = ""
restartPolicyType = "never"
