[build]
builder = "nixpacks"
buildCommand = "npm ci --only=production && npm install nx@latest && npx nx build gateway-service"

[deploy]
preDeployCommand = ["npx prisma migrate deploy --schema=libs/api/database/prisma/schema.prisma"]
startCommand = "node apps/api/gateway/dist/main.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
