[build]
builder = "dockerfile"
dockerfilePath = "apps/api/billing/Dockerfile"
watchPatterns = [
  "apps/api/billing/**",
  "libs/api/**",
  "nx.json",
  "package.json",
  "tsconfig*.json"
]

[deploy]
healthcheckPath = ""
restartPolicyType = "never"
